spring:
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mysecurity?autoReconnect=true&useSSL=false
    druid:
          initialSize: 5
          minIdle: 5
          maxActive: 20
          maxWait: 60000
          timeBetweenEvictionRunsMillis: 60000
          minEvictableIdleTimeMillis: 300000
          validationQuery: SELECT 1
          testWhileIdle: true
          testOnBorrow: true
          testOnReturn: false
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          filters: stat,wall
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
          stat-view-servlet:
            allow: 127.0.0.1
  session:
    store-type: redis
  http:
    multipart:
      max-file-size: 300Mb #单个文件的大小
      max-request-size: 600Mb
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 100000

  mail:
    host: smtp.exmail.qq.com
    username: admin@wenfan.club
    password: Wenfan0934
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
server:
  port: 8060
  session:
    timeout: 86400
  connection-timeout: 180000


token:
  expire:
    seconds: 720000
    jwtSecret: wenfan666@

mybatis:
  mapperLocations: classpath*:club/wenfan/security/mapper/xml/*.xml
  type-aliases-package: club.wenfan.security.entity
logging:
  level:
    club.wenfan.security.mapper : debug
  file: youtube.log
  path: var\local\youtube\log 



